version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_USER: dma_user
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: dma_db
    ports:
      - "5499:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
